# Generated by Django 4.2.6 on 2023-10-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clearmind', '0002_fixadas_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixadas',
            name='data',
            field=models.DateTimeField(verbose_name='Sunday, October 29, 2023 12:15:28'),
        ),
    ]
