# Generated by Django 4.2.6 on 2023-10-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clearmind', '0003_alter_fixadas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixadas',
            name='data',
            field=models.CharField(default='', max_length=100),
        ),
    ]
