# Generated by Django 4.2.6 on 2023-10-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clearmind', '0006_alter_listas_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listas',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
